# Generated by Django 4.2.6 on 2024-01-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='investor.investor'),
        ),
    ]
